<?php

declare(strict_types=1);

namespace Liip\Serializer;

interface DeserializerHandlerInterface
{
    /**
     * Generate the PHP code to deserialize the object from the value.
     *
     * This method is called while generating the code for the deserializer, not at runtime of deserialization. You need
     * to generate PHP code that can be included into the deserialization function generated by the Liip serializer.
     * Use the $arrayPath to access the data structure that the object was serialized to. Use $className to know which
     * object to instantiate.
     *
     * @param class-string $className
     * @param string       $arrayPath Contains a PHP expression for the property value, e.g. "$model->id"
     */
    public function generateDeserializeExpression(string $className, string $arrayPath): string;

    /**
     * @return class-string[]
     */
    public function getDeserializationClasses(): array;
}
