<?php

declare(strict_types=1);

namespace Liip\Serializer;

interface SerializerHandlerInterface
{
    /**
     * Generate the PHP code to serialize the value from the object.
     *
     * This method is called while generating the code for the serializer, not at runtime of serialization. You need
     * to generate PHP code that can be included into the serialization function generated by the Liip serializer.
     * Use the $modelPath to access the object and return the value for the json array. Use $className to know which
     * class is serialized.
     *
     * @param class-string $className
     * @param string       $modelPath Contains a PHP expression for the raw array value, e.g. $array['id']
     */
    public function generateSerializeExpression(string $className, string $modelPath): string;

    /**
     * @return class-string[]
     */
    public function getSerializationClasses(): array;
}
